[build]
  command = "node netlify-build.js && ng build --configuration=production"
  publish = "dist/grocery-app/browser"
  functions = "netlify/functions"

[dev]
  command = "ng serve"
  port = 4000
  targetPort = 4200
  publish = "dist/grocery-app"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200